[Feat] local login 전략 생성
boostcampwm-2024/web21-boostproject pull request #127
Opened 2024-11-10 06:12 UTC by begong313

## 관련 이슈 번호
close #61 

## 작업 내용
- passport local 전략생성
- USER 생성, USER 찾기 코드생성
- db 스키마 IMPORT 에러 수정
- 테스트 코드 작성 ( CLAUDE를 통하여 생성)

## PR 포인트
- 테스트 코드의 경우 시간부족과 작성방법 러닝커브로 인해 ai를 통하여 작성하였습니다.
    - ai 를 통해 테스트 코드 작성하는 방법이 옳은가에 대해서 한번 다같이 생각해보면 좋을 것 같습니다! 

## 고민과 학습내용
### typeORM 스키마 import 에러
```bash
TypeORMError: Entity metadata for Ticle#applicants was not found
```
- typeorm config 중 entitiy import하는 방법을 `글로벌 패턴` 에서 `autoLoadEntities`로 변경한 후 서버 실행 시 에러가 났음
- autoLoadEntityies는 다른 모듈 어딘가에서 `typeOrmModules.forFeature([entity])`를 통하여 등록된 entity들을 자동으로 import
- 사용하지 않는 applicant 등의 entity들이 import 되지 않은 채 관계가 설정되어 나는 에러였음.
[학습 노션 링크에도 업뎃완료](https://simeunseo.notion.site/TypeORM-2891d93b3a354ab290c25514f1caea19?pvs=4) 

## 스크린샷

2024-11-10 08:28 UTC, seoko97 requested changes

2024-11-10 08:28 UTC, seoko97 commented on apps/api/src/auth/auth.service.ts
> +    const user = await this.userService.findUser(username); // user 태이블에 username이 있는지 확인, 있으면 user 객체 반환
p3:
이런 주석은 제거해주세요!

2024-11-10 08:28 UTC, seoko97 commented on apps/api/src/auth/strategy/google.strategy.ts
> +// export class GoogleStrategy extends PassportStrategy(Strategy, 'google') {}
주석처리한 이유는 무엇인가요?

2024-11-10 08:28 UTC, seoko97 commented on apps/api/src/auth/auth.service.ts
> +    return null;
p3:

```ts
if (!user) {
   return null;
}
```

이런식으로 변경하면 좋을 것 같습니다

2024-11-10 10:26 UTC, begong313 commented on apps/api/src/auth/strategy/google.strategy.ts
> +// export class GoogleStrategy extends PassportStrategy(Strategy, 'google') {}
세팅 하면서 일단 틀을 잡아놓으려고 코드를 적어놨었는데, setting값이 없어서 실행 중 에러가나서 제거했습니다!! 현재 브랜치에서는 안쓰는코드라 삭제하도록하겠습니다!

2024-11-10 10:33 UTC, begong313 commented on apps/api/src/auth/auth.service.ts
> +    return null;
변경완료했습니다!

2024-11-10 10:33 UTC, begong313 commented on apps/api/src/auth/auth.service.ts
> +    const user = await this.userService.findUser(username); // user 태이블에 username이 있는지 확인, 있으면 user 객체 반환
수정완료했습니다!

2024-11-11 01:07 UTC, seoko97 approved these changes

2024-11-11 02:18 UTC, simeunseo approved these changes
고생하셨습니다!!

개인적으로 ai와 함께 테스트 코드를 짜는 것 좋다고 생각합니다..ㅎㅎ
스스로 테스트 해야 할 상황&응답에 대한 정의를 명확히 하고 그걸 ai한테 전달할 수 있다면요!

2024-11-11 02:18 UTC, simeunseo commented on apps/api/src/user/dto/create-user.dto.ts
> +}
`Q`
혹시 이 DTO는 local login과 social login을 한꺼번에 아우르는 걸까요?
local login에 대한 DTO같은데 socialId 필드가 있는 것이 의문이어서 여쭤봅니다!

2024-11-11 02:18 UTC, simeunseo commented on apps/api/src/user/dto/create-user.dto.ts
> +}
추가로 introduce는 티클 개설시 작성하는 발표자 소개와는 별개인건지,
만약 별개라면 use DTO에 introduce가 꼭 필요할지 여쭤보고싶습니다!

2024-11-11 02:31 UTC, begong313 commented
> 고생하셨습니다!!
> 
> 개인적으로 ai와 함께 테스트 코드를 짜는 것 좋다고 생각합니다..ㅎㅎ 스스로 테스트 해야 할 상황&응답에 대한 정의를 명확히 하고 그걸 ai한테 전달할 수 있다면요!

이것저것 시도중인데 프롬폼트를 잘짜서 계속 테스트코드를 생성해봐야겠네요!!

2024-11-11 02:39 UTC, begong313 commented on apps/api/src/user/dto/create-user.dto.ts
> +}
> `Q` 혹시 이 DTO는 local login과 social login을 한꺼번에 아우르는 걸까요? local login에 대한 DTO같은데 socialId 필드가 있는 것이 의문이어서 여쭤봅니다!

<img width="1064" alt="스크린샷 2024-11-05 오후 1 28 14" src="https://github.com/user-attachments/assets/be7baca8-3cee-4111-9ab6-cbcd0d1627c7">

- 말씀해 주신 점때문에 social login에 대한 table을 따로 나누는게 맞나에 대한 얘기를 했었는데, 굳이 그렇게까지 세세하게 나눌필요가 없을것같다는 결론이 났었습니다!!(우리의 서비스에서는 나눠서관리하는게 과도하다는 느낌...)
- 그래서 userTable에 넣을 데이터들을 한번에 정의하게되었습니다!! 
    - dto entity코드에서 default설정이 안되어있는것들이 있어서 추후 entity 수정되면 바뀔 수 있습니다!! 
    - 도메인 별로 다시 나누고 리팩토링하면서 많이 변경될거같네요
    

> 추가로 introduce는 티클 개설시 작성하는 발표자 소개와는 별개인건지, 만약 별개라면 use DTO에 introduce가 꼭 필요할지 여쭤보고싶습니다!

별개라고 생각하지만 마이페이지 기능이 생길 수 있다보니(높은 확률로 만들 듯) user에도 introduce를 넣어주었던걸로 기억합니다!

2024-11-11 02:39 UTC, merged

2024-11-11 03:17 UTC, simeunseo commented on apps/api/src/user/dto/create-user.dto.ts
> +}
아 이해했습니다! 상세히 설명해주셔서 감사합니다!!!