[Feat] TextArea 공통 컴포넌트 구현
boostcampwm-2024/web21-boostproject pull request #132
Opened 2024-11-10 13:57 UTC by simeunseo

## 관련 이슈 번호

- close #130

## 작업 내용
### TextArea 공통 컴포넌트 구현
TextInput과 유사합니다.
- label, description, required 값에 따른 조건부 렌더링
- errorMessage가 존재할 경우 렌더링
- maxLength가 존재할 경우 글자수 카운터 렌더링
- 웹 접근성을 고려한 속성 추가
- react-hook-form을 적용할 것을 고려하여 uncontrolled로 구현

### TextInput 공통 컴포넌트 수정
- width를 prop으로 넘겨서 사이즈를 조절하도록 했었는데 동적 스타일링이 어려운 tailwind의 특성에 따라서 사이즈를 sm md lg로 나누어 정해진 크기를 렌더링할 수 있도록 했습니다.
- TextArea도 마찬가지로 동일한 방식을 적용했습니다.
- TextInput은 controlled로 구현했었는데 마찬가지로 react-hook-form을 고려하여 uncontrolled로 변경했습니다.

## PR 포인트
- Input 컴포넌트들은 실제 티클 개설 폼을 구현하면서 조금씩 달라질 수 있을 것 같습니다~!

## 고민과 학습내용
### controlled form과 uncontrolled form
#### controlled form
- React가 form 데이터를 완전히 제어하는 방식
- form의 값이 state에 의해 관리됨
- 입력할 때마다 리렌더링이 일어나는 것이 단점

#### uncontrolled form
- form 데이터를 DOM 자체에서 관리하는 방식
- state를 사용하지 않고 ref를 통해 필요할 때만 값에 접근
- 불필요한 리렌더링을 방지

### react-hook-form
react-hook-form을 사용하면 uncontrolled form을 사용하면서도 복잡한 validation을 즉각적으로 처리할 수 있으며 렌더링 성능을 챙기면서도 로직을 깔끔하게 관리할 수 있음

## 스크린샷
### 모든 옵션 적용, 사이즈 sm
![image](https://github.com/user-attachments/assets/8a5f1dec-1617-433e-9c3d-30769fb4d9ae)

### 사이즈 md - 발표자 자기소개에 쓰일 예정
![image](https://github.com/user-attachments/assets/34c77d33-3a31-48af-bb50-ce1ac5d1f294)

### 사이즈 lg - 티클 소개에 쓰일 예정
![image](https://github.com/user-attachments/assets/8fe1d7cb-a7f8-4576-8271-c41d0f4767d0)

2024-11-10 15:12 UTC, begong313 approved these changes
👏

2024-11-10 15:18 UTC, seoko97 requested changes

2024-11-10 15:18 UTC, seoko97 commented on apps/web/src/components/common/TextArea/index.tsx
> +        <label htmlFor={label} className="text-title2 text-main">
`text-title2`와 `text-main`이 같이 들어가는 이유가 무엇인가요?

2024-11-10 15:18 UTC, seoko97 commented on apps/web/src/components/common/TextArea/index.tsx
> +          >{`${defaultValue?.toString().length ?? 0}/${maxLength}`}</p>
p4:
`defaultValue`로 string이 아닌값이 들어오는 경우가 있나요? 기본 style type을 상속받아 처리하려다 보니 다음과 같이 진행된 것 같습니다!

저희 프로젝트에서 `textarea`에 특수성을 생각해봤을 때 interface 내부에서 defaultValue에 대한 타입 정의를 `string`으로 설정하는 것이 좋을 것 같습니다!

2024-11-10 15:18 UTC, seoko97 commented on apps/web/src/components/common/TextInput/index.tsx
> +      [SIZE_VARIANTS.lg]: 'w-full',
p4:
`lg` 라는 네이밍보다 `full`이면 더 좋을 것 같습니다

2024-11-10 15:18 UTC, seoko97 commented on apps/web/src/components/common/TextInput/index.tsx
> +  const handleCounter = (e: ChangeEvent<HTMLInputElement>) => {
p2:
함수의 이름에 `counter`가 들어가는데 내부 기능은 textContent를 변경하는 것 같습니다! 정확하게 어떤 기능을 담당하는 건가요?

2024-11-10 15:18 UTC, seoko97 commented on apps/web/src/components/common/TextArea/index.tsx
> +import ExclamationIc from '@/assets/icons/exclamation.svg?react';
앗 icon을 사용할 때 `?react` 라는 suffix를 붙여줘야 되는군요... 참고하겠습니다!

2024-11-10 15:18 UTC, seoko97 commented on apps/web/src/components/common/TextArea/index.tsx
> +import { ChangeEvent, forwardRef, Ref, TextareaHTMLAttributes, useRef } from 'react';
p5:
뭔가 `react`가 가장 위로 왔으면 좋겠는데... 따로 설정 추가할까요?

2024-11-10 15:24 UTC, simeunseo commented on apps/web/src/components/common/TextArea/index.tsx
> +          >{`${defaultValue?.toString().length ?? 0}/${maxLength}`}</p>
`TextareaHTMLAttributes<HTMLTextAreaElement`에서 제공하는 기본 type을 최대한 유지하는 것이 괜찮지 않을까 생각했는데, 실제로 저희 프로젝트에서 defaultValue가 string 외의 것이 될 일은 없다보니 필요없는 toString()을 지우고 타입을 더 좁히는 것도 좋을 것 같네요! 반영하겠습니다 감사합니다!! :)

2024-11-10 15:24 UTC, simeunseo commented on apps/web/src/components/common/TextInput/index.tsx
> +      [SIZE_VARIANTS.lg]: 'w-full',
왠지 sm md lg 세가지를 맞춰야할것만 같았는데... full이 더 타당한 것 같습니다 ㅎㅎ 반영하겠습니다

2024-11-10 15:27 UTC, simeunseo commented on apps/web/src/components/common/TextInput/index.tsx
> +  const handleCounter = (e: ChangeEvent<HTMLInputElement>) => {
![image](https://github.com/user-attachments/assets/9b891e87-706d-44e2-a63a-fe42fb3e3fb4)

우하단에 표기되는 글자수 표기를 관리하는 onChange handler입니다!
따라서 input에 onChange 이벤트가 일어날 때 글자수 텍스트를 변경하는 역할을 하고 있습니다.
이 글자수 표기 영역을 counter라고 명명하고 handleCounter라는 이름을 짓게 되었어요!
더 좋은 네이밍이 있을까요?

2024-11-10 15:29 UTC, simeunseo commented on apps/web/src/components/common/TextArea/index.tsx
> +import ExclamationIc from '@/assets/icons/exclamation.svg?react';
맞습니다 svgr 4버전부터 앨리어싱을 생략하기 위해 추가된 문법으로 알고있습니다!

2024-11-10 15:30 UTC, simeunseo commented on apps/web/src/components/common/TextArea/index.tsx
> +import { ChangeEvent, forwardRef, Ref, TextareaHTMLAttributes, useRef } from 'react';
흠 사용자 정의 함수가 제일 위로 오는군요 어떤게 일반적인지 잘 모르겠네요..ㅎㅎ 사용자 정의함수가 가장 아래에 오는게 더 보기 좋을까요? 저는 크게 상관없습니다!!

2024-11-11 02:44 UTC, Fixtar approved these changes
어렵습니다... 세미나... 열심히 듣겠습니다...

2024-11-11 07:12 UTC, seoko97 approved these changes

2024-11-11 07:14 UTC, merged