[Feat] 티클 생성 API 구현
boostcampwm-2024/web21-boostproject pull request #133
Opened 2024-11-10 14:07 UTC by Fixtar

## 관련 이슈 번호
#13 

- close #{이슈번호}

## 작업 내용
티클 생성 api를 구현하였습니다. 
이 과정에서 tag 를 붙이기 위하여 tag가 있다면 조회하고, 없다면 생성하는 로직을 추가했습니다. 
티클 생성후 메인이나, 티클 상세페이지로 이동한다고 생각했기에 return 값을 티클의 id값으로 설정했습니다. 
-> api response 바로 만들겠습니다~

## PR 포인트
- tag 로직을 위한 모듈을 만들어야 할지
태그관련 로직은 대부분 티클 생성과 조회에서만 사용됩니다. 따라서 이를 모듈로 분리하는게 맞을지? 고민입니다.
- spread 문법
- api Return 값 

## 고민과 학습내용
## Spread 문법
spread 문법이란 `…Data` 처럼 사용하여 데이터를 매핑하는 문법입니다.

### Spread 문법이 안전하지 않은 이유
1. 얕은 복사
2. 타입 안전성 부족
3. 덮어쓰기 가능
4. 비동기 작업후 참조문제

### 코드 작성 근거

- 유효성 검사는 아직 추가하지 않았지만 `zod` 를 추가할 예정입니다. 이를 이용하여 해결할 수 있을 것이라고 생각합니다.
- 비동기 작업 후 참조 문제는 비동기 작업에서 `데이터의 변경이 일어날 때` 발생합니다. 
예를들어 위의 코드에서는 Tag에 해당하는 작업이 dto를 변경하는 경우가 있습니다. 
또한, spread 문법을 사용하려는 객체가 비동기로 처리되고 resolve 가 되지 않았을 때 발생합니다.
⇒ 현재는 이런일이 없기에 그대로 사용해도 괜찮다고 판단했습니다

## 스크린샷

2024-11-10 15:21 UTC, begong313 commented on apps/api/src/ticle/ticle.service.ts
> +      return foundTags;
`P2` 계속 db에 접근하며 하나씩 찾아서 성능 적 문제가 생길 것 같습니다.
gpt에게 물어보니
```Typescript
// 1. 전달받은 태그 이름으로 이미 존재하는 태그들을 한 번에 조회
    const existingTags = await this.tagRepository.find({
      where: { name: tags },
    });

    const existingTagNames = existingTags.map(tag => tag.name);
    const toCreate = tags.filter(tagName => !existingTagNames.includes(tagName));

    // 2. 생성할 태그 이름이 있는 경우, 일괄 삽입 후 생성된 태그 반환
    if (toCreate.length > 0) {
      await this.tagRepository.insert(
        toCreate.map(tagName => ({ name: tagName }))
      );
    }

    // 3. 다시 한 번 조회해서 모든 태그 반환
    return await this.tagRepository.find({
      where: { name: tags },
    });
```
이렇게 한번에 조회하고 insert하는 방법도 있나봐요!!

2024-11-10 15:22 UTC, begong313 approved these changes

2024-11-10 15:22 UTC, begong313 commented on apps/api/src/ticle/ticle.service.ts
> +      return foundTags;
`P2` 계속 db에 접근하며 하나씩 찾아서 성능 적 문제가 생길 것 같습니다.
gpt에게 물어보니
```Typescript
// 1. 전달받은 태그 이름으로 이미 존재하는 태그들을 한 번에 조회
    const existingTags = await this.tagRepository.find({
      where: { name: tags },
    });

    const existingTagNames = existingTags.map(tag => tag.name);
    const toCreate = tags.filter(tagName => !existingTagNames.includes(tagName));

    // 2. 생성할 태그 이름이 있는 경우, 일괄 삽입 후 생성된 태그 반환
    if (toCreate.length > 0) {
      await this.tagRepository.insert(
        toCreate.map(tagName => ({ name: tagName }))
      );
    }

    // 3. 다시 한 번 조회해서 모든 태그 반환
    return await this.tagRepository.find({
      where: { name: tags },
    });
```
이렇게 한번에 조회하고 insert하는 방법도 있나봐요!!

2024-11-10 15:22 UTC, begong313 requested changes

2024-11-10 15:22 UTC, begong313 commented on apps/api/src/ticle/ticle.service.ts
> +      }
`P2` 계속 db에 접근하며 하나씩 찾아서 성능 적 문제가 생길 것 같습니다.
gpt에게 물어보니
```Typescript
// 1. 전달받은 태그 이름으로 이미 존재하는 태그들을 한 번에 조회
    const existingTags = await this.tagRepository.find({
      where: { name: tags },
    });

    const existingTagNames = existingTags.map(tag => tag.name);
    const toCreate = tags.filter(tagName => !existingTagNames.includes(tagName));

    // 2. 생성할 태그 이름이 있는 경우, 일괄 삽입 후 생성된 태그 반환
    if (toCreate.length > 0) {
      await this.tagRepository.insert(
        toCreate.map(tagName => ({ name: tagName }))
      );
    }

    // 3. 다시 한 번 조회해서 모든 태그 반환
    return await this.tagRepository.find({
      where: { name: tags },
    });
```
이렇게 한번에 조회하고 insert하는 방법도 있나봐요!!

2024-11-10 15:28 UTC, seoko97 requested changes

2024-11-10 15:28 UTC, seoko97 commented on apps/api/src/ticle/ticle.service.ts
> +      throw new Error(`Failed to create ticle `);
p1:
`NestJs`에서 제공하는 `exception`을 사용하는게 좋을 것 같습니다! 

[관련 문서](https://docs.nestjs.com/exception-filters)

2024-11-10 15:28 UTC, seoko97 commented on apps/api/src/ticle/ticle.service.ts
> +        applicants: [],
p3:
default value를 통해 초기 값을 등록할 수 없나요?

2024-11-10 15:28 UTC, seoko97 commented on apps/api/src/ticle/ticle.service.ts
> +    @InjectRepository(Ticle)
p3:
따로 repository를 구현하지 않고 바로 주입해서 사용하고 있군요.. Repository class를 따로 구현한다면 DB 접근시 중복으로 선언하는 코드를 줄일 수 있을 것 같습니다! 다만 우선순위가 높지 않아 추후 리펙토링 과정에서 적용해보는 것이 좋을 것 같습니다!

2024-11-10 15:28 UTC, seoko97 commented on apps/api/src/ticle/ticle.service.ts
> +  async checkAndCreateTags(tags: string[]): Promise<Tag[]> {
p2: 
다음 함수는 이름과 같이 2가지 작업을 수행하고 있습니다.

각 기능별로 함수를 분리하는 것이 더 좋을 것 같습니다.

2024-11-10 15:28 UTC, seoko97 commented on apps/api/src/ticle/ticle.module.ts
> +  imports: [TypeOrmModule.forFeature([Ticle, Tag, Summary, Applicant])],
p2:
`Tag`, `Summary`, `Applicant` 엔티티에 경우 비지니스 로직을 구현하지 않는건가요? `TicleModule` 내부에서 엔티티를 추가하는 이유가 무엇인가요?

2024-11-10 15:29 UTC, seoko97 commented on apps/api/src/ticle/ticle.service.ts
> +      }
맞네요 이걸 놓쳤네요. findIOne을 태그의 수만큼 실행하면 부하가 심할 것 같습니다!

2024-11-10 15:33 UTC, begong313 commented on apps/api/src/ticle/ticle.service.ts
> +        applicants: [],
entity에서 default value로 OPEN으로 설정하게 하면될거같습니다!

2024-11-10 17:14 UTC, Fixtar commented on apps/api/src/ticle/ticle.module.ts
> +  imports: [TypeOrmModule.forFeature([Ticle, Tag, Summary, Applicant])],
엔티티가 없으면 실행이 안되는 경우가 있어서 일단 붙여놨습니다. 
필요한 곳으로 옮겨두겠습니다!

2024-11-11 03:08 UTC, Jieun1ee approved these changes

2024-11-11 03:08 UTC, Jieun1ee commented on apps/api/src/ticle/ticle.service.ts
> +        name: In(tags),
이렇게 하면 IN 절로 조회가 가능하군여...!!!? 또 하나 배워갑니다

2024-11-11 03:22 UTC, simeunseo requested changes

2024-11-11 03:22 UTC, simeunseo commented on apps/api/src/ticle/dto/createTicleDto.ts
> +};
`P1` 
티클 생성할 때 진행 날짜, 시작 시간, 종료 시간이 필요한데 진행 날짜가 없는 것 같습니다!?!

2024-11-11 03:22 UTC, simeunseo commented on apps/api/src/ticle/ticle.service.ts
> +  async findExistingTags(tags: string[]) {
이건 이미 존재하는 tag를 생성하려고 했을 때 그 tag는 제외하기 위한 예외처리라고 보면 될까요??

2024-11-11 03:23 UTC, simeunseo reviewed
테이블 설계 하실 때 혹시 이 내용 확인하셨을까요? (확인차 여쭤봅니다)

![image](https://github.com/user-attachments/assets/6b191398-02ac-4127-bbef-2884b400b7b1)

제가 잘 몰라서 여쭙는데, 이런 validation 코드가 따로 없어보이는데 어떻게 처리되는건지 궁금합니다!

2024-11-11 04:36 UTC, Fixtar commented on apps/api/src/ticle/dto/createTicleDto.ts
> +};
진행 날짜를 startTime, endTime으로 생각하고 작성했습니다
예를들어 2024-11-11 19:00 (startTime), 2024-11-11 20:00 (endTime) 이런식으로요!

2024-11-11 04:37 UTC, Fixtar commented on apps/api/src/ticle/ticle.service.ts
> +      }
수정했습니다~! 검토 한번 부탁드립니다!!

2024-11-11 04:38 UTC, simeunseo commented on apps/api/src/ticle/dto/createTicleDto.ts
> +};
아~ 그러면 클라에서 그렇게 넘겨줘야겠군요! 확인했습니다!

2024-11-11 04:39 UTC, Fixtar commented
> 테이블 설계 하실 때 혹시 이 내용 확인하셨을까요? (확인차 여쭤봅니다)
> 
> ![image](https://private-user-images.githubusercontent.com/55528304/384769108-6b191398-02ac-4127-bbef-2884b400b7b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDAxMDgsIm5iZiI6MTczMTI5OTgwOCwicGF0aCI6Ii81NTUyODMwNC8zODQ3NjkxMDgtNmIxOTEzOTgtMDJhYy00MTI3LWJiZWYtMjg4NGI0MDBiN2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA0MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNThlNjhkMjkxY2E3ZWJmNWQ4OGEzYTI0NzYxMjVmMjQ4NWE1NDlkMzMzMmU5ODdkZjVjMmI2OWQ0NTgzZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6WciecnjuWVUNJ12fsrEc3bftX4I7Dl0zR7qMLJBcUw)
> 
> 제가 잘 몰라서 여쭙는데, 이런 validation 코드가 따로 없어보이는데 어떻게 처리되는건지 궁금합니다!

zod로 validation 처리를 할 예정입니다! 다만, 아직 도입하지 않아서 현재는 validation이 없는 상태입니다

2024-11-11 04:39 UTC, simeunseo approved these changes

2024-11-11 05:53 UTC, seoko97 approved these changes
고생하셨습니다!

2024-11-11 06:11 UTC, begong313 approved these changes

2024-11-11 06:14 UTC, merged