[Feat] SearchInput 공통 컴포넌트 구현
boostcampwm-2024/web21-boostproject pull request #138
Opened 2024-11-10 16:03 UTC by simeunseo

## 관련 이슈 번호

- close #134 

## 작업 내용
- SearchInput 공통 컴포넌트 구현
- controlled input으로 구현
- onClear prop을 받아 X버튼 클릭시 검색어 초기화
- onSearch prop을 받아 검색 기능을 사용처에서 처리
- size prop을 받아 TextInput과 동일하게 sm, md, full을 선택 가능
- 접근성 관련 속성 추가
- 엔터 입력시에도 검색이 동작하도록 키보드 인터랙션 추가
- input에 대해 type='search' 속성을 추가했기 때문에 esc를 누르면 검색어가 초기화되는 기본 인터랙션이 있음

## PR 포인트
- TextArea 컴포넌트 구현 내용을 branch chaining해서 작업했기 때문에 관련 커밋이 포함되어있는 점 양해부탁드립니다!
- 디바운스나 즉각적인 검색 결과 표시 등을 위해 부모 컴포넌트에서 value값을 알아야할 가능성이 높은 searchField의 특성을 고려하여 controlled input으로 구현했습니다.
- 기본적으로 TextInput과 동일한 스타일링을 가지고있기 때문에, TextInput에서 사용된 스타일링 로직을 export해서 재사용했습니다. 이 때 lint 룰 중에 `'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],`라는 룰이 있는데, fast refresh를 위해서 컴포넌트 파일에서는 컴포넌트만 export하도록 강제하는 룰입니다. 이 룰 때문에 스타일링 로직을 export할 수가 없어서 이 파일에 대해서만 해당 룰을 비활성화 했습니다. lint 비활성화는 웬만하면 피하려하는데, 그러려면 이 스타일링 로직을 따로 파일로 빼야합니다. 하지만 기본적으로 TextInput의 스타일이기 때문에 외부로 빼는것보다는 TextInput 컴포넌트 파일에 응집되어있는게 더 좋다고 생각하여, 예외적으로 lint 비활성화를 했습니다.

## 고민과 학습내용

## 스크린샷

https://github.com/user-attachments/assets/07d7222a-277f-460e-bd47-0e7aae9c81dd

2024-11-11 02:30 UTC, begong313 approved these changes

2024-11-11 02:30 UTC, begong313 commented on apps/web/src/components/common/TextArea/index.tsx
> +} as const;
`P5` - `textput.index` 에서 사용하는 validation_state와 size_variants랑 겹치는 느낌인데 따로 분리해도 좋을거같아요!

2024-11-11 02:32 UTC, seoko97 requested changes

2024-11-11 02:32 UTC, seoko97 commented on apps/web/src/components/common/SearchInput/index.tsx
> +    }
p3:
```suggestion
    if (e.key !== 'Enter') {
       return;
    }
    
    onSearch(value);
```

🫡

2024-11-11 02:32 UTC, seoko97 commented on apps/web/src/components/common/SearchInput/index.tsx
> +          <button type="button" onClick={() => onSearch(value)} aria-label="검색하기">
p1:
추후 작업상황을 고려하더라도 실제 UI와 기능 정의는 나누는게 맞다고 생각합니다!

한 줄짜리 함수더라도 변수에 할당하는 것은 어떻게 생각하시나요?

2024-11-11 02:32 UTC, seoko97 commented on apps/web/src/components/common/TextArea/index.tsx
> +    <div className={cn('flex flex-col gap-1.5')}>
여기서 `cn` 함수는 어떤 역할을 하나요?

2024-11-11 02:32 UTC, seoko97 commented on apps/web/src/components/common/TextArea/index.tsx
> +        }
궁금한 점이 있습니다! `aria` prefix가 붙은 custom attribute에 경우 어떤 역할을 하나요? 1인 개발시에는 잘 고려하지 않다보니 궁금합니다!

2024-11-11 02:32 UTC, seoko97 commented on apps/web/src/components/common/TextInput/index.tsx
> +            <ExclamationIc className="fill-error" width={9} />
p2:
이런 경우 height 값도 명시적으로 표현하는 것이 좋을 것 같습니다!

2024-11-11 02:34 UTC, simeunseo commented on apps/web/src/components/common/SearchInput/index.tsx
> +    }
엇 왜 이렇게 변경해야하는걸까요?!
Enter키가 아닌 모든 키에 대해 검색을 실행하는 건가요??

2024-11-11 03:03 UTC, Fixtar commented on apps/web/src/components/common/SearchInput/index.tsx
> +    }
저는 early return 으로 Enter키가 아닐때를 먼저 검사해서 종료시키는 것으로 이해했습니다
여러 조건을 검사해야할 경우 각 조건에 따라 Return 해버리고, 실행 로직이 if문 안에 들어가지 않도록하여 가독성에 장점이 있는 것으로 알고 있습니다!!

2024-11-11 03:29 UTC, simeunseo commented on apps/web/src/components/common/SearchInput/index.tsx
> +    }
아아아 맞네요 early return인데 제가 잘못 이해했군요! 설명 감사드립니다!!

2024-11-12 01:57 UTC, simeunseo commented on apps/web/src/components/common/TextArea/index.tsx
> +} as const;
오 좋습니다~ 반영했습니다!

2024-11-12 02:09 UTC, seoko97 approved these changes

2024-11-12 02:11 UTC, simeunseo commented on apps/web/src/components/common/SearchInput/index.tsx
> +          <button type="button" onClick={() => onSearch(value)} aria-label="검색하기">
-> 일단 그대로 두고 최적화 작업할 때 필요하다면 분리하는 것으로 구두 논의 완료!

2024-11-12 02:12 UTC, simeunseo commented on apps/web/src/components/common/TextArea/index.tsx
> +    <div className={cn('flex flex-col gap-1.5')}>
ㅋㅋㅋ 발견 감사합니다!

2024-11-12 02:19 UTC, simeunseo commented on apps/web/src/components/common/TextArea/index.tsx
> +        }
- `aria-invalid`는 해당 입력이 유효하지 않다는 것을 나타내고 오류 메시지도 함께 읽어준다고 합니다! 따라서 errorMessage가 존재할 때 aria-invalid를 true로 만들어주는 것입니다
- `aria-describedby`는 이 요소에 대한 설명을 연결해주는 속성입니다. 따라서 errorMessage가 존재할 때는 에러메시지를 표시하는 영역으로 설정해주면 현재 이 input에 대해 에러메시지가 설명해주고있다는 걸 연결해주고, 스크린리더가 이해하기 쉽게 읽어준다고 합니다!

참고로 aria는 Accessible Rich Internet Applications의 줄임말이라고 하네요~

2024-11-12 04:11 UTC, merged