[Feat] Avatar Component 구현
boostcampwm-2024/web21-boostproject pull request #159
Opened 2024-11-11 15:06 UTC by seoko97

## 관련 이슈 번호

- close #151 

## 작업 내용

- Avatar 컴포넌트 구현
- 기본 이미지 추가
- tailwind config 오타 수정

## 스크린샷

<img width="392" alt="스크린샷 2024-11-12 오전 12 02 42" src="https://github.com/user-attachments/assets/4314311b-d790-4047-94bf-6d67e25539b5">

2024-11-11 18:29 UTC, begong313 approved these changes

2024-11-11 18:29 UTC, begong313 commented on apps/web/tailwind.config.ts
> +        weak: 'var(--grey-700)',
<img width="571" alt="스크린샷 2024-11-12 오전 3 28 26" src="https://github.com/user-attachments/assets/b4006a56-ea4f-42a5-9870-5a6d0842ccb7">
영국식 회색이였군요

2024-11-12 01:30 UTC, simeunseo requested changes

2024-11-12 01:30 UTC, simeunseo commented on apps/web/src/assets/images/person.png
`P3`
이거 혹시 왜 png로 저장하셨을까요?? svg로 변경해주실 수 있을까요?

2024-11-12 01:30 UTC, simeunseo commented on apps/web/src/components/common/Avatar/index.tsx
> +      }}
`P2` 
inline style은 최소화하면 좋을거같은데 className에 넣지 않으신 이유가 있을까요?

2024-11-12 01:30 UTC, simeunseo commented on apps/web/tailwind.config.ts
> +        weak: 'var(--grey-700)',
ㅋㅋㅋㅋ 오  쟤 혼자 gray로 되어있었군요

2024-11-12 01:30 UTC, simeunseo commented on apps/web/src/components/common/Avatar/index.tsx
> +      }}
아 동적 스타일링이어서 그런 거 같은데 혹시 tailwind에서는 이렇게 inline style로 대응하는게 최선인걸까요,,?
어차피 피그마 상에 사이즈가 3개로 딱 나뉘어있으니 sm md lg로 prop 받아도 괜찮을 것 같다는 생각입니다

2024-11-12 01:50 UTC, simeunseo reviewed
제가 테스트해봤을 때는 img 대신 svg를 넣어도 문제가 없기는 했는데요!!
근데 이게 직접 이미지 src를 넣을 수 있다는 점을 간과했네요 ㅎㅎㅎ
그래서 png로 들어가도 괜찮을거같아요~! 오히려 코드가 간단해져서 좋을거같습니다

prop 받아오는 컨벤션만 저희 정한대로 수정 부탁드릴게요!!

2024-11-12 04:33 UTC, seoko97 commented on apps/web/src/components/common/Avatar/index.tsx
> +      }}
아쉽게도 `tailwind`에서 동적 스타일을 구현하는 방법은 인라인 스타일을 사용하는 방법밖에 없습니다ㅠㅠ 말씀해주신 사이즈 이외에 사용하는 경우가 없다면 사이즈를 미리 생성하도록 하겠습니다!

2024-11-12 05:20 UTC, simeunseo approved these changes

2024-11-12 06:03 UTC, merged