[Feat] 참여자 목록 조회 API 구현
boostcampwm-2024/web21-boostproject pull request #163
Opened 2024-11-11 16:20 UTC by Jieun1ee

## 관련 이슈 번호

- close #85

## 작업 내용
- 개설한 speaker 입장에서 참여자 목록에 대한 조회가 가능하도록 구현.
- User 정보 중에서 nickname과 profileImageUrl만 담음.

## PR 포인트
- applicant 테이블에서 해당하는 ticleId로 해당하는 user들을 찾고, 피그마와 동일하게 user 정보들 중에서 user의 닉네임과 프로필이미지의 url만 리턴하도록 구현하였습니다.

## 고민과 학습내용
- 피그마 상에는 프로필이미지와 이름만 뜨도록 구현이 되어서 이렇게만 했습니다. 신청할 때 중복 검사도 할 것 같아서 우선은 따로 검증하는 로직은 추가하지 않았고, db에 저장되는 순서대로 꺼내올 것 같아서 applicant의 createdAt도 사용하지 않았습니다. 참여자 정보들을 꺼내오는 순서들이 상관이 없다면 이대로 진행하면 될 것 같습니다!
```ts
return applicants.map((applicant) => ({
        nickname: applicant.user.nickname,
        profileImageUrl: applicant.user.profileImageUrl,
      }));
``` 

## 스크린샷

2024-11-11 16:50 UTC, begong313 requested changes

2024-11-11 16:50 UTC, begong313 commented on apps/api/src/dashboard/dashboard.service.ts
> +        profileImageUrl: applicant.user.profileImageUrl,
P1 - 이부분  select 문을 사용하면 map을 안써도 되는거같습니다!
이전 커밋에도 있던거같은데 수정부탁드려요!

2024-11-11 17:00 UTC, Jieun1ee commented on apps/api/src/dashboard/dashboard.service.ts
> +        profileImageUrl: applicant.user.profileImageUrl,
map으로 배열처리를 해주려고 하다보니까 그렇게 됐네요.. select문이 더 간단한걸 잘몰랐습니다 ㅜㅜ 수정완료했습니다~!

2024-11-11 17:03 UTC, begong313 approved these changes

2024-11-13 05:48 UTC, Fixtar approved these changes

2024-11-13 06:51 UTC, merged