[Feat] Header Component 구현
boostcampwm-2024/web21-boostproject pull request #167
Opened 2024-11-12 02:36 UTC by seoko97

## 관련 이슈 번호

- close #162

## 작업 내용

- Header Component 구현

## PR 포인트

- url param에 따라 경로 수정을 진행해야 합니다

## 스크린샷

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/c8a09c5c-ec82-4704-ba05-1cadfaa4eb83">

2024-11-12 04:24 UTC, simeunseo requested changes

2024-11-12 04:24 UTC, simeunseo commented on apps/web/tailwind.config.ts
> +        hover: 'var(--purple-700)',
`P3`
혹시 hover 색상 grey-800으로 가면 어떠실까요?ㅎㅎ purple-700이 다른데서 안쓰이는 색이라 조금 어색해보여서요!!

2024-11-12 04:24 UTC, simeunseo commented on apps/web/src/components/Header/index.tsx
> +        <Link to="/ticle/open" className={NAV_STYLE}>
`P2`
이거 제가 의도한 거는 그냥 "/" 루트페이지이긴 했거든요! 오픈 페이지로 이동할거면 메뉴이름을 티클 개설로 바꾸거나 해야할거같아요

2024-11-12 05:13 UTC, seoko97 commented on apps/web/src/components/Header/index.tsx
> +        <Link to="/ticle/open" className={NAV_STYLE}>
아직 명확하게 헤더에 어떤 데이터가 정해지지 않아 한번 얘기해보면 좋을 것 같습니다!

2024-11-12 05:20 UTC, simeunseo approved these changes

2024-11-13 13:02 UTC, begong313 approved these changes

2024-11-13 15:51 UTC, merged