[Feat] Dashboard API 엔드포인트 수정
boostcampwm-2024/web21-boostproject pull request #180
Opened 2024-11-13 13:03 UTC by Jieun1ee

## 관련 이슈 번호

- close #166

## 작업 내용
- Dashboard 엔드포인트에 created, applied 를 지웠습니다.

## PR 포인트
- endpoint 수정
- 추후 JWTAuthGuard 도입 예정이므로 이 부분은 참고해주세요.

## 고민과 학습내용
- Controller의 getTicleList에서 speakerId와 UserId 둘 중 한가지를 받도록 수정하였습니다.
- Controller에서 에러를 던지지 않도록 Service에서 getTicleList 함수를 만들어 조건문을 사용한 후
```
  async getTicleList(speakerId?: number, userId?: number) {
    if (speakerId) {
      return await this.getCreatedTicleList(speakerId);
    } else if (userId) {
      return await this.getAppliedTicleList(userId);
    } else {
      throw new BadRequestException('speakerId 또는 userId 중 하나는 필요합니다.');
    }
  }
```
다음과 같이 둘 중에 하나가 없는 경우 에러를 던지는 코드를 추가하였습니다. 

## 스크린샷

2024-11-13 17:27 UTC, Fixtar requested changes

2024-11-13 17:27 UTC, Fixtar commented on apps/api/src/dashboard/dashboard.controller.ts
> +    return await this.dashboardService.getTicleList(speakerId, userId);
P1
대시 보드에서의 조회가 Filter 역할이라고 생각합니다. 
1. 로그인한 유저가 speaker인 경우 
2. 로그인한 유저가 applicant인 경우 
저는 Filter 에 적절한 것은 `query param` 으로 speaker 인지 Applicant인지 판단하는 것이라고 생각합니다.!! 
`uesrId`와 `speakerId` 두가지가 존재하는 이유를 잘 모르겠습니다! 


-  참고자료
저번 피드백과 관련하여 path parameter 와 query parameter 를 비교해 둔 링크입니다! 
https://velog.io/@juno97/API-Path-parameter-VS-Query-Parameter-%EA%B8%B0%EB%A1%9D%EC%9A%A9

2024-11-14 03:25 UTC, begong313 approved these changes

2024-11-17 12:51 UTC, seoko97 approved these changes
고생하셨습니다!

사용하지 않는 변수에 경우 `_` 로 변수 이름을 변경하면 오류가 lint상에 걸리지 않도록 설정해놨습니다! 해당 기능을 활용해주시면 감사하겠습니다!

2024-11-17 12:51 UTC, seoko97 commented on apps/api/src/dashboard/dashboard.controller.ts
> +  async getTicleList(@Request() req: any, @Query('isSpeaker') isSpeaker: boolean) {
p3:
`req`의 타입은 express의 `Request` 타입을 사용하면 좋을 것 같습니다! 그런데 lint 상에서 에러 발생 안했나요??

2024-11-17 15:35 UTC, begong313 requested changes

2024-11-17 15:35 UTC, begong313 commented on apps/api/src/dashboard/dashboard.controller.ts
> +    }
p2:
이부분 return에 await 빼주세요!

2024-11-17 16:01 UTC, Jieun1ee commented on apps/api/src/dashboard/dashboard.controller.ts
> +  async getTicleList(@Request() req: any, @Query('isSpeaker') isSpeaker: boolean) {
네 ! 따로 에러는 발생하지 않았습니다 ! 근데 nest의 Request 대신 왜 Express의 Request를 사용하는 걸까요 !?

2024-11-17 16:17 UTC, begong313 approved these changes

2024-11-17 16:50 UTC, Fixtar approved these changes

2024-11-18 00:59 UTC, merged