[Feat] 로그인 성공 시 '/' 로 리다이렉션
boostcampwm-2024/web21-boostproject pull request #198
Opened 2024-11-18 05:47 UTC by begong313

## 관련 이슈 번호

- close #188 

## 작업 내용
- 로그인 (로컬, google, github) 성공 시 '/' (localhost://5173) 으로 리다이렉트
- 쿠키에 jwt토큰 삽입
- PASSPORT STRATEGY 리턴 타입 통일

## PR 포인트
### `환경변수 업데이트 되었습니다`

## 고민과 학습내용

## 스크린샷
![ezgif com-video-to-gif-converter (3)](https://github.com/user-attachments/assets/2ebc602c-5066-4ab5-b540-0b0ef0fa080b)

- 클라이언트에서 이용 시
```typescript
// API 요청 시
const response = await fetch('/api/something', {
  headers: {
    'Authorization': `Bearer ${accessToken}`,
    'Content-Type': 'application/json'
  }
});

```

2024-11-18 06:36 UTC, seoko97 approved these changes

2024-11-19 01:00 UTC, seoko97 requested changes

2024-11-19 01:00 UTC, seoko97 commented on apps/api/src/auth/auth.controller.ts
> +      secure: process.env.NODE_ENV === 'production',
p2:
`configService`를 사용해주세요

2024-11-19 01:04 UTC, begong313 commented on apps/api/src/auth/auth.controller.ts
> +      secure: process.env.NODE_ENV === 'production',
수정했습니당

2024-11-19 03:52 UTC, seoko97 approved these changes

2024-11-19 16:19 UTC, Fixtar commented on apps/api/src/user/user.service.ts
> +    } catch {
`Q`
이렇게 catch 해도 잡히나요?? 
InternalServerErrorException() 이걸 사용하신 이유도 궁금합니다

2024-11-19 16:57 UTC, begong313 commented on apps/api/src/user/user.service.ts
> +    } catch {
혹여나 write시 db에러가 발생하면 서버가 터질까봐 붙여놨습니다!! read는 거의 error가 안날거같은데 write는 적정돼서요....
로깅같은게 추가되면 에러이유 탐색가능하게 변경할거같습니다!
혹시 서버 안터지게 하는 좋은방법있을까요..??

2024-11-19 17:58 UTC, Fixtar commented on apps/api/src/user/user.service.ts
> +    } catch {
어렵네요 멘토님께 한번 여쭤볼까요?

2024-11-19 17:58 UTC, Fixtar approved these changes

2024-11-19 18:02 UTC, merged