[Feat] GetDashboardListQueryDto 생성
boostcampwm-2024/web21-boostproject pull request #229
Opened 2024-11-20 16:56 UTC by Jieun1ee

## 관련 이슈 번호

- close #228 

## 작업 내용
- 쿼리의 타입을 검사하기 위해 dto를 만들어 zod를 설정했습니다.

## PR 포인트
- 꼭 필요한 쿼리들은 필수로, status같은 필터링 조건은 optional로 설정했습니다.

## 고민과 학습내용

## 스크린샷
<img width="829" alt="image" src="https://github.com/user-attachments/assets/d228bc1b-6a80-4709-9978-a8adcf104ea7">

2024-11-20 17:30 UTC, seoko97 requested changes

2024-11-20 17:30 UTC, seoko97 commented on apps/api/src/dashboard/dto/getDashboardListQueryDto.ts
> +    .refine((val) => !isNaN(val) && val > 0, '페이지 번호는 0보다 커야 합니다'),
p1:
`packages/types`폴더로 이동해 주세요.

1. `packages/types`의 `dashboard/{이벤트 이름}.ts` 생성
2.  `dashboard/index.ts` 에서 `{이벤트 이름}.ts` 내보내기

ex)
```ts
// dashboard/getDashboardList.ts
export const GetDashboardListQuerySchema = z.object({ ... })
export type GetDashboardListQueryType = z.infer<typeof GetDashboardListQuerySchema>;

// dashboard/index.ts
export * from "./getDashboardList"
```

p2: 
number type으로 설정하면 되지 않나요?

2024-11-21 04:18 UTC, begong313 approved these changes

2024-11-21 04:18 UTC, begong313 commented on apps/api/src/dashboard/dashboard.controller.ts
> +      );
`p4` - query.page, query.pageSize, query.status가 중복돼서 사용중이니 변수로뺴서 넣어도될거같습니다!

2024-11-21 06:18 UTC, Fixtar approved these changes

2024-11-21 06:49 UTC, seoko97 approved these changes

2024-11-21 07:05 UTC, merged