[Feat] 로그인 페이지 구현
boostcampwm-2024/web21-boostproject pull request #286
Opened 2024-11-26 06:16 UTC by simeunseo

## 관련 이슈 번호

- close #283 
- close #285

## 작업 내용
- oauth 로그인 구현
- 게스트 로그인 구현
- 로그인 로딩 인디케이터 추가
- 그 외 자잘한 UI 오류 해결

## PR 포인트
게스트 로그인이 원래 POST로 구현되어있었는데 CORS에러가 나는 문제로 GET으로 변경했습니다.

## 고민과 학습내용

## 스크린샷

https://github.com/user-attachments/assets/1c51d961-0795-4f30-ae70-106fe692747c

2024-11-26 15:34 UTC, begong313 approved these changes
👏

2024-11-26 17:10 UTC, seoko97 requested changes

2024-11-26 17:10 UTC, seoko97 commented on apps/api/src/auth/auth.controller.ts
> +  @Get('guest/login')
Q:
cors 에러가 발생한다면 `main.ts`에서 cors 설정을 진행해주면 되는 것 아닌가요?  메서드를 변경한 이유가 있을까요?

2024-11-26 17:10 UTC, seoko97 commented on apps/api/src/auth/auth.service.ts
> +      profileImageUrl: catImageUrl,
p2:
기본 프로필 이미지에 경우 `nullable`하게 변경하거나 `/`으로 접근시 `web/public`의 정적 파일에 접근할 수 있는 것을 이용하는 것은 어떨까요? (ex: `/cat-image.png`, vite에 경우 `/`로 바로 public 폴더에 접근 가능합니다) 

이미지를 가져오기 위해 `fetch` 요청을 할 이유가 없다고 생각합니다

2024-11-26 17:10 UTC, seoko97 commented on apps/web/src/api/auth.ts
> +};
p1:
`axios`를 통해 요청을 진행하지 않는건가요? location을 직접 변경하는 이유가 무엇인가요?

2024-11-26 17:36 UTC, simeunseo commented on apps/api/src/auth/auth.service.ts
> +      profileImageUrl: catImageUrl,
아 이건 여러 게스트 유저를 만들어서 더미를 쌓아놓을 때 기본 이미지보다는 랜덤한 고양이 이미지 들어오는게 단순히 귀엽고 보기 좋을거같아서 넣기는 했습니다 😅 혹시 우려되는 문제가 있을까요? 🥲

2024-11-26 17:37 UTC, simeunseo commented on apps/api/src/auth/auth.controller.ts
> +  @Get('guest/login')
cors 설정을 해도 해결되지 않는 문제였습니다. 잠깐 알아보니 상당히 복잡하더라구요... 일단 중요한부분은 아니라고 생각해서 빠른 조치를 취하게 되었스빈다

2024-11-26 17:39 UTC, simeunseo commented on apps/web/src/api/auth.ts
> +};
로그인 버튼을 눌렀을 때 해당 주소에서 GET을 해야하기 때문에 axios GET 요청이 아닌 링크 이동으로 구현하게 되었습니다!

2024-11-26 17:40 UTC, seoko97 commented on apps/api/src/auth/auth.service.ts
> +      profileImageUrl: catImageUrl,
http 요청으로 인해 성능상 좋지 않을 것으로 생성되지만... 고양이 귀엽죠... 우선 두고 테스트 진행하며 문제 발생시 변경해도 좋을 것 같습니다!!! 고양이 지켜!!

2024-11-26 17:46 UTC, simeunseo commented on apps/api/src/auth/auth.controller.ts
> +  @Get('guest/login')
https://www.milk717.com/gomterview-2

우연히 발견한게 또 곰터뷰 개발자분의 아티클인데 ㅋㅋㅋ 상당한 트러블 슈팅이 있었던것으로 보입니다 흠 이 부분을 집중해서 해결해봐야할지 고민이 됩니다...

2024-11-27 02:10 UTC, seoko97 approved these changes
페어프로그래밍을 통한 질문 답변 완료

2024-11-27 05:53 UTC, merged