[Feat] React + Vite + Typescript 초기 설정
boostcampwm-2024/web21-boostproject pull request #97
Opened 2024-11-04 14:41 UTC by seoko97

## 관련 이슈 번호

- close #64

## 작업 내용

- React + Vite + Typescript 초기 설정
- 기존 `packages` 에 정의한 설정을 확장하여 설정 진행
- `vite-tsconfig-paths`를 통한 절대 경로 인식
- vite에서 react `public` 폴더의 경로를 `/`으로 설정하여 발생하는 eslint 오류 해결

## 스크린샷

|![image.png](https://github.com/user-attachments/assets/78138175-4e3d-4ff9-a825-3b27244b58c9)|![image2.png](https://github.com/user-attachments/assets/6a246d30-5268-42a6-b25f-3986fa4e8d97)|
|--|--|
|경로 오류|타입 이름 오류|

|<img width="1275" alt="image" src="https://github.com/user-attachments/assets/64c54a41-2e43-4e80-bf2e-e71e1195bd6f">|
|--|
|`pnpm dev` 명령 실행시 서버 실행|

2024-11-04 14:54 UTC, simeunseo requested changes
빠른 작업 너무 감사합니다 석호님!!

반드시 해야하는 것들은 아니지만 초기 세팅 PR에서 미리 해두면 좋을 자잘한 작업들에 대해 코멘트 남겨놨습니다! 확인해주시면 감사하겠습니다 🙇🙇

2024-11-04 14:54 UTC, simeunseo commented on apps/web/.eslintrc.cjs
`P1`
react 프로젝트를 생성하면서 web이라는 폴더가 만들어진 것 같은데,
web 폴더로 빼지 않고 현재 web 하위에 있는 파일을 전부 client 폴더로 옮겨주시면 어떨까요?

2024-11-04 14:54 UTC, simeunseo commented on apps/web/README.md
`P2`
`README.md`를 비롯해 `public/vite.svg`, `App.css`, `assets/react.svg`, `index.css` 이 필요 없는 파일들은 미리 제거해주시면 프로젝트가 깔끔하게 유지될 것 같아요! ☺️

2024-11-04 14:54 UTC, simeunseo commented on apps/web/src/App.tsx
`P2`
App.tsx도 불필요한 초기 코드 없이 빈 태그로만 남겨주시면 더 좋을 것 같습니다!!

2024-11-04 14:54 UTC, simeunseo commented on apps/web/index.html
> +<html lang="en">
`P1` 여기 "ko"로 변경 부탁드리겠습니다!

2024-11-04 14:54 UTC, simeunseo commented on apps/web/index.html
> +    <title>Vite + React + TS</title>
title도 미리 `Ticle`로 변경해 주시면 좋을 것 같아요!

2024-11-04 16:05 UTC, seoko97 commented on apps/web/.eslintrc.cjs
`apps` 라는 디렉토리에 네이밍에 맞게 `web`으로 수정했습니다. 이전으로 되돌리는게 괜찮으면 수정하겠습니다!

2024-11-04 16:12 UTC, simeunseo commented on apps/web/.eslintrc.cjs
아 검색해보니 turborepo로 모노레포를 구성할 때 apps/web이라는 네이밍이 관용적으로 많이 쓰이는 것 같네요! 제가 잘 몰랐습니다.
알아봤을 땐 web이 브라우저 상에서 동작하는 클라이언트를 나타내기 위해 쓰이는 네이밍인 것 같아요.
그렇다면 기존의 client라는 폴더는 지우고 web이라는 폴더로 통합하면 어떨까 해요!

다음은 클로드가 추천해준 폴더 네이밍입니다 ㅎㅎ
```
apps/
  ├── web/          # 프론트엔드 메인 앱
  ├── admin/        # 관리자 프론트엔드
  ├── api/          # 메인 백엔드 API 서버
  └── worker/       # 백그라운드 작업 서버
```

2024-11-05 02:10 UTC, Jieun1ee approved these changes

2024-11-05 02:20 UTC, begong313 approved these changes

2024-11-05 02:20 UTC, simeunseo approved these changes

2024-11-05 02:20 UTC, merged